# Generated by Django 4.1.6 on 2023-04-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0018_playlist_music_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Album', 'Album'), ('Bollywood', 'Bollywood'), ('Hollywood', 'Hollywood'), ('Tollywood', 'Tollywood')], default='Album', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('Engligh', 'English'), ('Rajasthani', 'Rajasthani'), ('Haryanvi', 'Haryanvi'), ('Punjabi', 'Punjabi'), ('Telugu', 'Telugu')], default='Hindi', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='productionHouse',
            field=models.CharField(choices=[('T-Series', 'T-Series'), ('Sony Music', 'Sony Music'), ('Zee Music Company', 'Zee Music Company'), ('Madhura Audio', 'Madhura Audio'), ('Saregama', 'Saregama'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(choices=[('Classical', 'Classical'), ('Romantic', 'Romantic'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Devotional', 'Devotional'), ('Bhajan', 'Bhajan'), ('Dance', 'Dance'), ('Disco', 'Disco'), ('Ghazal', 'Ghazal'), ('Qawwali', 'Qawwali'), ('Muntha Masala', 'Muntha Masala')], default='Classical', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.CharField(choices=[('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1995', '1995'), ('1990', '1990'), ('1985', '1985')], default='2021', max_length=20),
        ),
    ]
